run:
  timeout: 5m

linters:
  disable:
    # errcheck is too strict for HTTP handlers where
    # c.Writer.Write errors on client disconnect are not actionable.
    # Disable project-wide and selectively handle at source if needed.
    - errcheck

issues:
  exclude-rules:
    # Ignore unchecked fmt.Sscanf in ETL parser — validation is done
    # after parsing via separate checks, not via Sscanf return value.
    - linters: [errcheck]
      text: "fmt.Sscanf"

    # HTTP response writer errors are non-actionable (client disconnect).
    - linters: [errcheck]
      text: "c.Writer.Write"
